### ISSUE TITLE
First feedback and feature request :)

### ISSUE THREAD

**Issue by iacobson** [efexen/ezmodex#1]
So fun! You can quickly put in a friendly format any kind of elixir project where you were expecting the results in the console.
One thing I'm missing a this time (or maybe there is, and I don't know how to use it), would be an input method. Something like, having a form field(which I saw I can already create), then a button that on click will run an assigned function, taking as arguments the form fields (maybe as a map, and if inside the form there are commas, transform them in lists  :) )

something like button -> click -> run function -> `function(%{field1: "aaa", field2: ["bbb", "ccc"]})`

**Comment by efexen** [comment]
Hey Dorian 👋 

Glad to hear you're finding it fun! That's the whole point.

There's quite a few things that need to be in place before the kind of story you're describing is possible such as support for more HTTP verbs, ability to extract data from the request, generating URLs etc.

I've got some ideas in place for how to make those kinds of things possible in the future but it's quite a way off and I need to think more about them so I'll close this for now hope that's ok 😄  I'll give you a heads up when something like that is possible.

Thanks,
 Ville
